### ISSUE TITLE
Websocketclient disconnected from websocketserver 

### ISSUE THREAD

**Issue by elC0mpa** [gilmaimon/ArduinoWebsockets#44] opened 2019-10-10 02:41 UTC
**Describe the bug**
Websocketclient is disconnected from websocketserver after client get a ping from server 

**To Reproduce**
Library : 0.4.11
Board : NodeMCU 
Steps to reproduce the behavior.

**Expected behavior**
I just hope the client doesn't disconnect from server 

**Additional context**
When this first happens, I thought it was because of a bug of the library, but i realized that the websocketserver makes a ping to the client when it receives a connection, so I decided to supress this behavior. After doing this, the websocketclient worked as expected, but i have no idea of what am i doing wrong. I suppose that i should modify the code when the client receives a Ping, something like answer with a pong, but i am not sure

**Comment by gilmaimon** [comment] 2019-10-10 09:12
> Steps to reproduce the behavior.

I'm sorry but there isn't enough info for me to reproduce or solve anything here. As you can guess pings should and are working fine for most people who use the library.

What is the server you are using? (software)
ESP debug logs can also be super useful.

**Comment by elC0mpa** [comment] 2019-10-10 22:51
Ok @gilmaimon, I understand you. Later i will post the code. The server I am using is from the Asyncwebserver library. I just want to know something, isn't supposed that each time the websocket receives a ping, it should respond with a pong? In that case, how can i do it, I mean, a pong. Have you think about sending the pong automatically?

**Comment by adelin-mcbsoft** [comment] 2019-10-10 23:06
As far as I tested, the library does handle the ping/pong situation. It does reply automatically with a pong every time receives a ping from the remote socket.

The server implementation you are using should reply with a pong to every ping request that is received from the micro-controller as well, if one is sent.

There's nothing that can be done on the library side, as it works accordingly.
See the RFCs [here](https://tools.ietf.org/html/rfc6455#section-5.5.3) for details about how ping/pong frame is handled.
Perhaps you just have to configure your websocket server accordingly.

**Comment by gilmaimon** [comment] 2019-10-10 23:17
@adelin-mcbsoft is absolutely right, the library will response with a `pong` every time a `ping` is received. The `pong` content will be the same as the content passed in the `ping`, as the RFC specifies.

Thanks for helping @adelin-mcbsoft.

> The server I am using is from the Asyncwebserver library

Cool, I'll look into it tomorrow. Hopefully I will understand what is the issue (either in my or their impl). If I won't be able to reproduce using a `Asyncwebserver` server, I will let you know so we can continue to try and find the issue.

**Comment by elC0mpa** [comment] 2019-10-11 00:44
You both are entirely right @gilmaimon and @adelin-mcbsoft, the library sends automatically a pong when it receives a ping. But there is a problem, when server receives the pong from the websocketclient wich is written using this library, it crashes. In order to detect the problem i programmed to log everything that is happening through serial. The problem is that, after receiving the pong answer from the client, it receives a binary message : 6e. In order to detect if the problem is related to the server, I did the same but using this library https://github.com/Links2004/arduinoWebSockets. The thing is that in this case, the server doesn't crash. So there should be a difference between your pong implementation and theirs. I hope this could Help you improving your library if i am right, I would like to keep using your library. Thanks in advance

**Comment by gilmaimon** [comment] 2019-10-11 10:44
Hi @elC0mpa,

I think the issue is fixed now. It seems like `Asyncwebserver` expects the whole websockets frame to come as one chunck, and I separate it for convince. This is not a "client bug" *per se*, but because changing it won't harm the correctness of the impl and will only increase compatibility with other versions and implementations of websockets - I'm happy to make it.

The changes are in `master`, can you clone the repo (or pull the changes) and see if the issue is fixed for you as well?

Gil.

**Comment by gilmaimon** [comment] 2019-10-11 13:51
I understand everything works well? @elC0mpa

**Comment by elC0mpa** [comment] 2019-10-11 15:19
Thanks for your answer @gilmaimon, I really appreciate your Help by changing the pong functionality of this library, I am busy right now but later i will clone the master branch and i will tell you if everything works as expected.

**Comment by gilmaimon** [comment] 2019-10-11 16:17
Great, I'm happy to help. I'll wait for your updates.

Actually not only pongs crash, any kind of message sent to the server used to crash it. So the change was essentially to how the library sends any kind of websockets message.

Gil.

**Comment by elC0mpa** [comment] 2019-10-12 04:47
It worked as expected @gilmaimon, now the websocketclient doesn't disconnect from server because the server doesn't crash. Thanks for your support, I really appreciate it, and i think this issue has helped to improve the compatibility of the library, so it has been good for you too. Thanks again

**Comment by gilmaimon** [comment] 2019-10-12 10:33
Great, I'll release it as a patch right now. 

I agree, it is a great change and I'm glad you surfaced this issue.

Thanks, 
Gil.

**Closed by gilmaimon** 2019-10-12 10:33 UTC
Labels: possible-bug

**Comment by elC0mpa** [comment] 2020-03-03 02:29
Hello @gilmaimon, I am here again 😂. The problem is that the server crashes each time the websocketclient is closed. I mean, when the server should detect that the client was disconnected, it crashes
